services:
  - type: web
    name: nestknot-backend
    env: node
    region: oregon # or choose your preferred region
    plan: free # or starter
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false # Requires you to enter it in the Render Dashboard
      - key: JWT_SECRET
        sync: false # Requires you to enter it in the Render Dashboard
